// ==========================================================================
// 📖 华文智能互动学习阅读器 - 词汇数据库 (data.js)
// ==========================================================================

const lessonTitle = "我只有八岁";

const lessonData = [
    // ===== 第1段 =====
    ["我", "wǒ", "I", "Saya"],
    ["只有", "zhǐ yǒu", "only", "hanya"],
    ["八岁", "bā suì", "eight years old", "lapan tahun"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["从来", "cóng lái", "never", "tidak pernah"],
    ["没有", "méi yǒu", "not", "tidak"],
    ["想过", "xiǎng guò", "thought", "terfikir"],
    ["我", "wǒ", "I", "saya"],
    ["会", "huì", "will", "akan"],
    ["死", "sǐ", "die", "mati"],
    ["，", "", "", ""],
    ["可是", "kě shì", "but", "tetapi"],
    ["现在", "xiàn zài", "now", "sekarang"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["真的", "zhēn de", "really", "benar-benar"],
    ["快要", "kuài yào", "about to", "hampir"],
    ["死了", "sǐ le", "dying", "mati"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    // ===== 第2段 =====
    ["我", "wǒ", "I", "Saya"],
    ["住在", "zhù zài", "live in", "tinggal di"],
    ["战区", "zhàn qū", "war zone", "zon perang"],
    ["里", "lǐ", "in", "dalam"],
    ["，", "", "", ""],
    ["这里", "zhè lǐ", "here", "di sini"],
    ["每天", "měi tiān", "every day", "setiap hari"],
    ["都", "dōu", "all", "semua"],
    ["有", "yǒu", "have", "ada"],
    ["炮声", "pào shēng", "sound of cannons", "bunyi meriam"],
    ["。", "", "", ""],
    ["爸爸", "bà ba", "father", "ayah"],
    ["妈妈", "mā ma", "mother", "ibu"],
    ["在", "zài", "at", "pada"],
    ["很久", "hěn jiǔ", "long time", "lama"],
    ["以前", "yǐ qián", "before", "dahulu"],
    ["就", "jiù", "already", "sudah"],
    ["去世了", "qù shì le", "passed away", "meninggal dunia"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["一直", "yī zhí", "always", "sentiasa"],
    ["跟着", "gēn zhe", "follow", "mengikuti"],
    ["姐姐", "jiě jie", "older sister", "kakak"],
    ["生活", "shēng huó", "live", "hidup"],
    ["。", "", "", ""],
    ["姐姐", "jiě jie", "older sister", "kakak"],
    ["对", "duì", "to", "terhadap"],
    ["我", "wǒ", "me", "saya"],
    ["很好", "hěn hǎo", "very good", "sangat baik"],
    ["，", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["总是", "zǒng shì", "always", "sentiasa"],
    ["把", "bǎ", "", ""],
    ["唯一", "wéi yī", "only", "satu-satunya"],
    ["的", "de", "", ""],
    ["食物", "shí wù", "food", "makanan"],
    ["留给", "liú gěi", "leave for", "tinggalkan untuk"],
    ["我", "wǒ", "me", "saya"],
    ["吃", "chī", "eat", "makan"],
    ["。", "", "", ""],
    ["可是", "kě shì", "but", "tetapi"],
    ["，", "", "", ""],
    ["现在", "xiàn zài", "now", "sekarang"],
    ["姐姐", "jiě jie", "older sister", "kakak"],
    ["也", "yě", "also", "juga"],
    ["不在了", "bù zài le", "no longer here", "tiada lagi"],
    ["，", "", "", ""],
    ["她", "tā", "she", "dia"],
    ["在", "zài", "in", "dalam"],
    ["一次", "yī cì", "one", "satu"],
    ["爆炸", "bào zhà", "explosion", "letupan"],
    ["中", "zhōng", "in", "dalam"],
    ["受了", "shòu le", "suffered", "mengalami"],
    ["重伤", "zhòng shāng", "serious injury", "cedera parah"],
    ["，", "", "", ""],
    ["没过", "méi guò", "not past", "tidak sampai"],
    ["几天", "jǐ tiān", "a few days", "beberapa hari"],
    ["就", "jiù", "then", "lalu"],
    ["离开", "lí kāi", "leave", "meninggalkan"],
    ["了", "le", "", ""],
    ["我", "wǒ", "me", "saya"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    // ===== 第3段 =====
    ["我", "wǒ", "I", "Saya"],
    ["一个人", "yī gè rén", "alone", "seorang diri"],
    ["在", "zài", "in", "di"],
    ["废墟", "fèi xū", "ruins", "runtuhan"],
    ["里", "lǐ", "in", "dalam"],
    ["走着", "zǒu zhe", "walking", "berjalan"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["感到", "gǎn dào", "feel", "merasa"],
    ["很", "hěn", "very", "sangat"],
    ["饿", "è", "hungry", "lapar"],
    ["，", "", "", ""],
    ["也", "yě", "also", "juga"],
    ["很", "hěn", "very", "sangat"],
    ["渴", "kě", "thirsty", "dahaga"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["看到", "kàn dào", "see", "melihat"],
    ["一群人", "yī qún rén", "a group of people", "sekumpulan orang"],
    ["在", "zài", "in", "sedang"],
    ["排队", "pái duì", "queue", "beratur"],
    ["领水", "lǐng shuǐ", "collect water", "mengambil air"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["也", "yě", "also", "juga"],
    ["跑过去", "pǎo guò qù", "run over", "berlari ke sana"],
    ["排队", "pái duì", "queue", "beratur"],
    ["。", "", "", ""],
    ["可是", "kě shì", "but", "tetapi"],
    ["，", "", "", ""],
    ["轮到", "lún dào", "turn", "giliran"],
    ["我", "wǒ", "me", "saya"],
    ["的", "de", "", ""],
    ["时候", "shí hou", "when", "apabila"],
    ["，", "", "", ""],
    ["水", "shuǐ", "water", "air"],
    ["已经", "yǐ jīng", "already", "sudah"],
    ["没有", "méi yǒu", "no more", "tiada"],
    ["了", "le", "", ""],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["坐在", "zuò zài", "sit at", "duduk di"],
    ["地上", "dì shàng", "ground", "tanah"],
    ["，", "", "", ""],
    ["看着", "kàn zhe", "watching", "melihat"],
    ["那些", "nà xiē", "those", "itu"],
    ["领到", "lǐng dào", "received", "mendapat"],
    ["水", "shuǐ", "water", "air"],
    ["的", "de", "", ""],
    ["人", "rén", "people", "orang"],
    ["，", "", "", ""],
    ["心里", "xīn lǐ", "in heart", "dalam hati"],
    ["很", "hěn", "very", "sangat"],
    ["难过", "nán guò", "sad", "sedih"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第4段

    // ===== 第4段 =====
    ["后来", "hòu lái", "later", "kemudian"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["病了", "bìng le", "sick", "sakit"],
    ["。", "", "", ""],
    ["我", "wǒ", "my", "saya"],
    ["的", "de", "", ""],
    ["身体", "shēn tǐ", "body", "badan"],
    ["很", "hěn", "very", "sangat"],
    ["烫", "tàng", "hot", "panas"],
    ["，", "", "", ""],
    ["头", "tóu", "head", "kepala"],
    ["也", "yě", "also", "juga"],
    ["很", "hěn", "very", "sangat"],
    ["痛", "tòng", "painful", "sakit"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["躺在", "tǎng zài", "lie in", "berbaring di"],
    ["一个", "yī gè", "a", "sebuah"],
    ["破旧", "pò jiù", "shabby", "usang"],
    ["的", "de", "", ""],
    ["帐篷", "zhàng péng", "tent", "khemah"],
    ["里", "lǐ", "in", "dalam"],
    ["，", "", "", ""],
    ["没有", "méi yǒu", "no", "tiada"],
    ["人", "rén", "person", "orang"],
    ["来", "lái", "come", "datang"],
    ["理", "lǐ", "care", "peduli"],
    ["我", "wǒ", "me", "saya"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["看到", "kàn dào", "see", "melihat"],
    ["窗外", "chuāng wài", "outside window", "di luar tingkap"],
    ["有", "yǒu", "have", "ada"],
    ["一棵", "yī kē", "a", "sebatang"],
    ["树", "shù", "tree", "pokok"],
    ["，", "", "", ""],
    ["树上", "shù shàng", "on the tree", "di atas pokok"],
    ["的", "de", "", ""],
    ["叶子", "yè zi", "leaves", "daun"],
    ["已经", "yǐ jīng", "already", "sudah"],
    ["落光", "luò guāng", "fallen off completely", "gugur habis"],
    ["了", "le", "", ""],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["突然", "tū rán", "suddenly", "tiba-tiba"],
    ["想到", "xiǎng dào", "think of", "terfikir"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["今年", "jīn nián", "this year", "tahun ini"],
    ["只有", "zhǐ yǒu", "only", "hanya"],
    ["八岁", "bā suì", "eight years old", "lapan tahun"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["还有", "hái yǒu", "still have", "masih ada"],
    ["很多", "hěn duō", "many", "banyak"],
    ["事情", "shì qíng", "things", "perkara"],
    ["没有", "méi yǒu", "not", "belum"],
    ["做", "zuò", "do", "buat"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["还", "hái", "still", "masih"],
    ["没", "méi", "not", "belum"],
    ["去过", "qù guò", "been to", "pernah pergi"],
    ["学校", "xué xiào", "school", "sekolah"],
    ["，", "", "", ""],
    ["还", "hái", "still", "masih"],
    ["没", "méi", "not", "belum"],
    ["穿过", "chuān guò", "worn", "memakai"],
    ["新衣服", "xīn yī fu", "new clothes", "baju baru"],
    ["，", "", "", ""],
    ["甚至", "shèn zhì", "even", "malah"],
    ["还", "hái", "still", "masih"],
    ["没", "méi", "not", "belum"],
    ["吃过", "chī guò", "eaten", "makan"],
    ["一顿", "yī dùn", "a meal", "satu hidangan"],
    ["饱饭", "bǎo fàn", "full meal", "makan kenyang"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第5段

    // ===== 第5段 =====
    ["炮声", "pào shēng", "sound of cannons", "bunyi meriam"],
    ["又", "yòu", "again", "lagi"],
    ["响了", "xiǎng le", "sounded", "berbunyi"],
    ["，", "", "", ""],
    ["大地", "dà dì", "earth", "bumi"],
    ["在", "zài", "is", "sedang"],
    ["震动", "zhèn dòng", "shaking", "bergegar"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["感到", "gǎn dào", "feel", "merasa"],
    ["很", "hěn", "very", "sangat"],
    ["害怕", "hài pà", "afraid", "takut"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["想", "xiǎng", "want", "mahu"],
    ["喊", "hǎn", "shout", "jerit"],
    ["救命", "jiù mìng", "help", "tolong"],
    ["，", "", "", ""],
    ["可是", "kě shì", "but", "tetapi"],
    ["我", "wǒ", "I", "Saya"],
    ["没有", "méi yǒu", "no", "tiada"],
    ["力气", "lì qi", "strength", "tenaga"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["看到", "kàn dào", "see", "melihat"],
    ["天空", "tiān kōng", "sky", "langit"],
    ["中", "zhōng", "in", "di"],
    ["有", "yǒu", "have", "ada"],
    ["很多", "hěn duō", "many", "banyak"],
    ["黑烟", "hēi yān", "black smoke", "asap hitam"],
    ["，", "", "", ""],
    ["阳光", "yáng guāng", "sunlight", "cahaya matahari"],
    ["都", "dōu", "all", "semua"],
    ["照", "zhào", "shine", "sinar"],
    ["不", "bù", "not", "tidak"],
    ["进来", "jìn lái", "enter", "masuk"],
    ["了", "le", "", ""],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第6段

    // ===== 第6段 =====
    ["我", "wǒ", "I", "Saya"],
    ["就要", "jiù yào", "about to", "akan"],
    ["死了", "sǐ le", "die", "mati"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["死", "sǐ", "die", "mati"],
    ["的", "de", "", ""],
    ["时候", "shí hou", "when", "apabila"],
    ["，", "", "", ""],
    ["身上", "shēn shàng", "body", "badan"],
    ["还", "hái", "still", "masih"],
    ["穿着", "chuān zhe", "wearing", "memakai"],
    ["那件", "nà jiàn", "that", "itu"],
    ["破旧", "pò jiù", "shabby", "usang"],
    ["的", "de", "", ""],
    ["、", "", "", ""],
    ["沾满", "zhān mǎn", "covered with", "penuh dengan"],
    ["灰尘", "huī chén", "dust", "debu"],
    ["的", "de", "", ""],
    ["衣服", "yī fu", "clothes", "baju"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["希望", "xī wàng", "hope", "harap"],
    ["我", "wǒ", "I", "saya"],
    ["死后", "sǐ hòu", "after death", "selepas mati"],
    ["，", "", "", ""],
    ["能", "néng", "can", "boleh"],
    ["去", "qù", "go", "pergi"],
    ["一个", "yī gè", "a", "satu"],
    ["没有", "méi yǒu", "without", "tanpa"],
    ["战争", "zhàn zhēng", "war", "perang"],
    ["的", "de", "", ""],
    ["地方", "dì fang", "place", "tempat"],
    ["。", "", "", ""],
    ["那里", "nà lǐ", "there", "sana"],
    ["有", "yǒu", "have", "ada"],
    ["蓝天", "lán tiān", "blue sky", "langit biru"],
    ["，", "", "", ""],
    ["有", "yǒu", "have", "ada"],
    ["白云", "bái yún", "white clouds", "awan putih"],
    ["，", "", "", ""],
    ["有", "yǒu", "have", "ada"],
    ["绿草", "lǜ cǎo", "green grass", "rumput hijau"],
    ["，", "", "", ""],
    ["还有", "hái yǒu", "also have", "masih ada"],
    ["吃不完", "chī bù wán", "endless food", "makanan tidak habis"],
    ["的", "de", "", ""],
    ["食物", "shí wù", "food", "makanan"],
    ["。", "", "", ""],
    ["最", "zuì", "most", "paling"],
    ["重要", "zhòng yào", "important", "penting"],
    ["的", "de", "", ""],
    ["是", "shì", "is", "ialah"],
    ["，", "", "", ""],
    ["那里", "nà lǐ", "there", "sana"],
    ["没有", "méi yǒu", "no", "tiada"],
    ["炮声", "pào shēng", "sound of cannons", "bunyi meriam"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第7段

    // ===== 第7段 =====
    ["我", "wǒ", "I", "Saya"],
    ["只有", "zhǐ yǒu", "only", "hanya"],
    ["八岁", "bā suì", "eight years old", "lapan tahun"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["我", "wǒ", "I", "Saya"],
    ["已经", "yǐ jīng", "already", "sudah"],
    ["看到", "kàn dào", "seen", "melihat"],
    ["了", "le", "", ""],
    ["这个", "zhè gè", "this", "ini"],
    ["世界", "shì jiè", "world", "dunia"],
    ["最", "zuì", "most", "paling"],
    ["残酷", "cán kù", "cruel", "kejam"],
    ["的", "de", "", ""],
    ["一面", "yī miàn", "side", "sebelah"],
    ["。", "", "", ""],
    ["我", "wǒ", "I", "Saya"],
    ["希望", "xī wàng", "hope", "harap"],
    ["那些", "nà xiē", "those", "itu"],
    ["还在", "hái zài", "still", "masih"],
    ["打仗", "dǎ zhàng", "fighting", "berperang"],
    ["的", "de", "", ""],
    ["人", "rén", "people", "orang"],
    ["，", "", "", ""],
    ["能", "néng", "can", "boleh"],
    ["看看", "kàn kàn", "look", "lihat"],
    ["像", "xiàng", "like", "seperti"],
    ["我", "wǒ", "me", "saya"],
    ["这样", "zhè yàng", "like this", "begini"],
    ["的", "de", "", ""],
    ["孩子", "hái zi", "child", "kanak-kanak"],
    ["。", "", "", ""],
    ["我们", "wǒ men", "we", "kami"],
    ["只", "zhǐ", "only", "hanya"],
    ["想", "xiǎng", "want", "mahu"],
    ["活着", "huó zhe", "live", "hidup"],
    ["，", "", "", ""],
    ["只", "zhǐ", "only", "hanya"],
    ["想", "xiǎng", "want", "mahu"],
    ["有", "yǒu", "have", "ada"],
    ["一个", "yī gè", "a", "satu"],
    ["家", "jiā", "home", "rumah"],
    ["。", "", "", ""],
];

// 如果使用模块导出，取消下一行注释；若通过 script 标签引入，则全局可用
// export { lessonTitle, lessonData };
